CREATE DATABASE IF NOT EXISTS pig_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE pig_db;

CREATE TABLE IF NOT EXISTS users (
  id          INT UNSIGNED      NOT NULL AUTO_INCREMENT,
  username    VARCHAR(50)       NOT NULL,
  email       VARCHAR(255)      NOT NULL UNIQUE,
  password    VARCHAR(255)      NOT NULL,
  created_at  DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;